name: lostinthetyrol
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Lost in the Tyrol
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#084f00'
    - '#afbea6'
    - '#808000'
    - '#80aa55'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
